version: '3.4'

services:
  odatawithoutauth:
    image: ${DOCKER_REGISTRY-}odatawithoutauth
    container_name: odatawithoutauth.api
    build:
      context: .
      dockerfile: ODataWithoutAuth/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
  vinyl.database:
    image: postgres:latest
    container_name: vinyl.database
    environment:
      POSTGRES_DB: vinyl
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./containers/vinyl-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "vinyl"]
      interval: 10s
      retries: 5